import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { config } from "@/lib/config";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { WalletConnectProvider } from "@/components/WalletConnectProvider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletConnectProvider initialState={initialState}>
          {children}
        </WalletConnectProvider>
      </body>
    </html>
  );
}
