import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { wagmiConfig } from "@/lib/wagmiConfig";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import { WalletConnectProvider } from "@/components/WalletConnectProvider";

import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "edo-dao",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get("cookie"),
  );

  return (
    <html lang="en">
      <body className={cn("bg-slate-600", inter.className)}>
        <WalletConnectProvider initialState={initialState}>
          <div className={"container p-5"}>{children}</div>
        </WalletConnectProvider>
      </body>
    </html>
  );
}
